sudo: required

services:
    - docker

language: python
script: 
    - python -m pytest -v
    
after_success:
    - sh deploy_dockrhub.sh
    - test "$TRAVIS_BRANCH" = "master" && sh deploy_heroku.sh